version: 2
jobs:
  ci:
    docker:
        - image: circleci/android:api-27-alpha
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run tests
          command: ./gradlew test
  cd:
    docker:
       - image: circleci/android:api-27-alpha

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: publish new version
          command: |
            git config --global user.email "ci@circleci.com"
            git config --global user.name "circleci"
            git commit -am "New version"
            git push --tags

workflows:
  version: 2
  ci-cd:
    jobs:
      - ci
      - cd:
          requires:
            - ci
          filters:
            branches:
              only:
                - /master*/